name: Scheduled Hackathon Scraper

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create Firebase key file
      run: echo '${{ secrets.FIREBASE_SECRET }}' > firebase_key.json
    
    - name: Run hackathon scraper
      run: python hackathon_scrape.py
    
    - name: Upload to Firebase
      run: python firebase_upload.py